add_newline = true

[character]
success_symbol = "ğŸ¦„ "
error_symbol = "[âœ—](bold red) "

[directory]
truncation_length = 4
truncate_to_repo = true
truncation_symbol = ".../"

[docker_context]
symbol = "ğŸ³ "

[git_branch]
symbol = "ğŸŒ± "
truncation_length = 100
truncation_symbol = ""

[git_commit]
commit_hash_length = 4
tag_symbol = " ğŸ· "

[golang]
format = "via [ğŸğŸ’¨ $version](bold cyan) "

[terraform]
format = "[ğŸğŸ’¨ $version$workspace]($style) "
